# Generated by Django 5.2.2 on 2025-12-25 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sertifikat nomi')),
                ('file', models.FileField(upload_to='certificates/', verbose_name='Fayl (rasm yoki PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan sana')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug (URL nomi)')),
                ('content', models.TextField(verbose_name='Maqola matni')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/blog', verbose_name='Rasm')),
                ('is_published', models.BooleanField(default=True, verbose_name='Post saytga joylanganmi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Postlar',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ism')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Telefon raqami')),
                ('question', models.TextField(max_length=200, verbose_name='Savol matni')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('answer_date', models.DateTimeField(blank=True, null=True, verbose_name='Javob berilgan vaqt')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Javob matni')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answered_questions', to=settings.AUTH_USER_MODEL, verbose_name='Javob bergan admin')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['-created'],
            },
        ),
    ]
