# Generated by Django 5.1.3 on 2026-01-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_image_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='phone_number',
            field=models.CharField(max_length=13, verbose_name='Telefon raqami'),
        ),
    ]
